name: Trigger Onboarding Batch Logic App

on:
  workflow_dispatch:
    inputs:
      jsonFile:
        description: 'Path to the JSON file inside the input folder
        required: true
        default: 'inputs/sample.json'

jobs:
  trigger-logic-app:
    runs-on: ubuntu-latest
    env:
      ONBOARDING_BATCH_LOGIC_APP_DEV_URL: ${{ secrets.ONBOARDING_BATCH_LOGIC_APP_DEV_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read JSON payload
        id: read_json
        run: |
          payload=$(cat ${{ github.event.inputs.jsonFile }})
          echo "payload<<EOF" >> $GITHUB_ENV
          echo "$payload" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Trigger Logic App
        run: |
          curl -X POST "${{ env.LOGIC_APP_URL }}" \
            -H "Content-Type: application/json" \
            -d "${{ env.payload }}"
