name: Execute Code Workflow

on:
  workflow_dispatch:

jobs:
  run-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get install jq

      - name: Execute steps from JSON
        run: |
          INPUTS=$(jq -c '.steps[]' inputs/steps.json)
          echo "$INPUTS" | while read -r step; do
            NAME=$(echo "$step" | jq -r '.name')
            ENDPOINT=$(echo "$step" | jq -r '.endpoint')
            PAYLOAD=$(echo "$step" | jq -c '.payload')

            echo "Executing $NAME..."
            RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST "$ENDPOINT" \
              -H "Content-Type: application/json" -d "$PAYLOAD")
            CODE=$(tail -n1 <<< "$RESPONSE")

            if [ "$CODE" -eq 200 ]; then
              echo "$NAME succeeded"
            else
              echo "$NAME failed with status $CODE"
              cat response.json
              echo "Sending notification..."
              python3 scripts/notify.py "$NAME" "$CODE"
            fi
          done

      - name: Pause for manual review
        if: always()
        run: echo "Please review the results and manually trigger the next workflow if needed."
